### ISSUE TITLE
Feature request: Add TSV/CSV Output

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/variant-linker#29]
`variant-linker` currently outputs results only in JSON format. Users require flat file formats like Tab-Separated Values (TSV) or Comma-Separated Values (CSV) for spreadsheet analysis, pipeline integration, and easier data sharing. The `--output` CLI option allows specifying CSV/TSV, but the implementation is missing.

**1. Description:**

This feature should be implemented **first** as it establishes core data flattening logic required by VCF output (#2) and streaming (#34).

Enhance variant-linker to output results in Tab-Separated Values (TSV) or Comma-Separated Values (CSV) flat file formats. Users require these formats for spreadsheet analysis, pipeline integration, and easier data sharing. The `--output` CLI option exists but needs implementation for TSV/CSV.

**2. Problem Context:**

*   Output is currently JSON only.
*   VEP annotation results are nested (especially `transcript_consequences`), requiring flattening for tabular output.

**3. Proposed Solution: Flatten by Consequence**

Implement functionality to format the nested VEP annotation results into standard TSV/CSV files using a **"flatten by consequence"** strategy as the primary and default method:

*   Each row in the output will represent a single transcript (or other feature) consequence.
*   Variant-level information (input variant, location, etc.) will be repeated on each consequence row belonging to that variant.
*   If a variant has no `transcript_consequences`, a single row representing the variant with its top-level information will be output, with consequence-specific columns having default (e.g., empty) values.
*   *(Optional/Future Scope): A different flattening strategy (e.g., one row per variant) could be considered later via a flag like `--flatten-strategy`, but is **not** part of this initial implementation.*

**4. Implementation Plan:**

*   **Step 1: Define Data Extraction Configuration & Logic (New Module: `src/dataExtractor.js` or similar)**
    *   [ ] Create a reusable configuration (`columnConfig`) defining default TSV/CSV columns, mapping headers to data paths within `annotationData`. Structure:
        ```javascript
        // Example entry
        {
          header: "GeneSymbol",         // Column header name
          path: "gene_symbol",          // Dot-notation path within the object
          isConsequenceLevel: true,    // Is path relative to consequence (true) or top-level annotation (false)?
          defaultValue: "",             // Value if path not found
          formatter: (value) => value || "" // Optional function to format extracted value
        }
        ```
    *   [ ] Implement a core helper function `extractFields(dataObject, fieldConfig)` to retrieve and format a single value based on one `fieldConfig` entry.
    *   [ ] Define the initial `columnConfig` array covering key variant and consequence fields (e.g., OriginalInput, VEPInput, Location, MostSevereConsequence, Impact, GeneSymbol, TranscriptID, ConsequenceTerms, HGVSc, HGVSp, CADD, etc.), ensuring correct `path` and `isConsequenceLevel` values.
*   **Step 2: Implement Flattening Function (`_flattenAnnotationData` in `variantLinkerProcessor.js`)**
    *   [ ] Create `_flattenAnnotationData(annotationData, columnConfig)`:
        *   Input: `annotationData` array, `columnConfig` array.
        *   Output: Array of flat row objects (`{ header1: value1, ... }`).
        *   Logic: Iterate through `annotationData`. For each `annotation`, extract top-level fields (`isConsequenceLevel: false`) using `extractFields`. If `transcript_consequences` exist, iterate through them, extract consequence-level fields (`isConsequenceLevel: true`) using `extractFields`, combine with top-level data, and add a row for each consequence. If no consequences exist, create one row with top-level data and default values for consequence-level fields.
*   **Step 3: Implement Tabular Formatting Function (`_formatToTabular` in `variantLinkerProcessor.js`)**
    *   [ ] Create `_formatToTabular(flatRows, columnConfig, delimiter, includeHeader)`:
        *   Input: Result from `_flattenAnnotationData`, `columnConfig`, delimiter (`\t` or `,`), `includeHeader` boolean.
        *   Output: Formatted TSV/CSV string.
        *   Logic: Get ordered headers from `columnConfig`. Add header row if requested. Iterate `flatRows`, get values in header order, apply CSV quoting if needed, join with delimiter, and join all rows with newlines.
*   **Step 4: Modify `filterAndFormatResults` (`variantLinkerProcessor.js`)**
    *   [ ] Update the `switch` statement: Define/import `columnConfig`. Call `_flattenAnnotationData`. Add `case 'CSV':` and `case 'TSV':` calling `_formatToTabular`.
*   **Step 5: Update CLI (`main.js`)**
    *   [ ] Ensure `validateParams` accepts 'CSV' and 'TSV'.
*   **Step 6: Testing (`test/variantLinkerProcessor.test.js` and `test/dataExtractor.test.js`)**
    *   [ ] Add unit tests for `extractFields`.
    *   [ ] Add unit tests for `_flattenAnnotationData` (single/multiple/no consequences, missing fields).
    *   [ ] Add unit tests for `_formatToTabular` (quoting, delimiters, header).
    *   [ ] Add integration tests for `filterAndFormatResults` ('CSV'/'TSV').
*   **Step 7: Documentation (`README.md`)**
    *   [ ] Update CLI usage examples for `--output CSV/TSV`.
    *   [ ] Document the **default "flatten by consequence"** strategy.
    *   [ ] List and describe the default columns.
    *   [ ] Explain array formatting (e.g., `&` delimiter) and missing data handling.

**5. Acceptance Criteria:**

*   [ ] Running `variant-linker --output CSV ...` generates a valid, comma-separated file based on the flatten-by-consequence strategy.
*   [ ] Running `variant-linker --output TSV ...` generates a valid, tab-separated file based on the flatten-by-consequence strategy.
*   [ ] Output correctly handles results from both single variant and batch processing inputs.
*   [ ] Variants with no transcript consequences are represented by a single row with top-level info and empty/default consequence columns.
*   [ ] Output includes a defined, documented set of default columns.
*   [ ] Array fields (e.g., ConsequenceTerms) are represented appropriately within a single cell (e.g., delimited by `&`).
*   [ ] Missing data is represented by empty/default cells.
*   [ ] CSV output correctly quotes fields containing commas, quotes, or newlines.
*   [ ] Automated tests verify the flattening logic and the structure/content of TSV/CSV output.
*   [ ] Documentation is updated.

**Comment by berntpopp** [comment]
This will require a flattening logic.
We could have different flattening logic on variant level or transcript level.
Similar logic could be applied to vcf output.
